trigger:
  branches:
    include:
      - main # Change this to the branch you want to trigger on

pool:
  vmImage: 'ubuntu-latest'

steps:
# Step 1: Checkout the code from your GitHub repository
- checkout: self
  displayName: 'Checkout Code from GitHub'

# Echo message for code checkout
- script: |
    echo "Code checkout completed successfully."
  displayName: 'Echo Code Checkout'
